services:
  web:
    build: .
    container_name: fastapi_app
    ports:
      - "8005:8005"
    depends_on:
      - db
    command: ["./wait-for-it.sh", "db:5432", "--", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8005", "--reload"]
    environment:
      DATABASE_URL: postgresql+asyncpg://azeem:azeem123@db:5432/TradingApp
    volumes:
      - .:/code

  db:
    image: postgres:15
    container_name: fastapi_db
    restart: always
    environment:
      POSTGRES_USER: azeem
      POSTGRES_PASSWORD: azeem123
      POSTGRES_DB: TradingApp
    ports:
      - "6543:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: